### ISSUE TITLE
Más información en clínicas: ¿Deberían abrirse o extenderse? 

### ISSUE THREAD

**Issue by Josegarcia89** [sindudasmx/sd#17]
Más información en clínicas: ¿Deberían abrirse como pop-up o extenderse sin una pantalla extra?

**Comment by jipster** [comment]
creo que deberías de clickearlo para más info como así
![image](https://cloud.githubusercontent.com/assets/5718530/21967858/09fd28d6-db54-11e6-9962-2dcbc65efc97.png)
pero tenemos que definir cómo se ve en movil
