### ISSUE TITLE
Rediseñar la barra de paginación

### ISSUE THREAD

**Issue by jipster** [sindudasmx/sd#28]
![image](https://cloud.githubusercontent.com/assets/5718530/21968117/df1843fa-db56-11e6-8100-4379f3cf98cd.png)
Recomendaría algo más estilizado y que ocupara el espacio en el ancho de las cajas de información

**Comment by Josegarcia89** [comment]
Esto corresponde a https://github.com/sindudasmx/sd/issues/19
