### ISSUE TITLE
Mejorar diseño y contenidos de navbar

### ISSUE THREAD

**Issue by Josegarcia89** [sindudasmx/sd#4]
La que va arrriba del header

**Comment by jipster** [comment]
![image](https://cloud.githubusercontent.com/assets/5718530/21967827/92e5ced8-db53-11e6-97d3-33fad8a33744.png)
esta navbar está buena

**Comment by Josegarcia89** [comment]
![navbar1](https://cloud.githubusercontent.com/assets/16548492/22130831/6f3139cc-de74-11e6-8edc-9b9392135583.jpg)
![navbar2](https://cloud.githubusercontent.com/assets/16548492/22130832/6f350caa-de74-11e6-91de-09c1fa57e31d.jpg)


que opinan de esto? @jipster @EduardoClark 
Que este fixed.

Encotré el código

http://materializecss.com/navbar.html

**Comment by Josegarcia89** [comment]
@EduardoClark 

Cambié esto:

![navbar-01](https://cloud.githubusercontent.com/assets/16548492/22230250/1bf39ac6-e1a2-11e6-88f8-1c2b874166ac.png)
![navbar-02](https://cloud.githubusercontent.com/assets/16548492/22230249/1bf388ba-e1a2-11e6-8d5c-969f44af1274.png)

http://materializecss.com/navbar.html

Le quité el gimmick de que se moviera. Más bien hice chico el tamaño y cambié el ícono.

¿Cómo te paso estas cosas?

La tipografía oficial es:
https://fonts.google.com/specimen/Roboto+Condensed
