### ISSUE TITLE
Dropdown - "¿Qué necesitas?

### ISSUE THREAD

**Issue by jipster** [sindudasmx/sd#40]
Revisar si el término si el término de "Anticuerpos antiHIV" es correcto 
![image](https://cloud.githubusercontent.com/assets/5718530/26039944/0c01d254-38e6-11e7-9eba-caa891d1ab05.png)

**Comment by EduardoClark** [comment]
Parece que ese es el termino, pero segun google es lo mismo que prueba elisa

**Comment by jipster** [comment]
Pero en la base de datos vienen diferenciados? No se pueden cambiar las que
tengan esta por prueba elisa @Josegarcia89

**Comment by Josegarcia89** [comment]
En la base de datos ya no hay más que "Confirmatoria" "Rápida" "Sanguínea"
Las opciones deben ser:

Prueba de VIH, Prueba Confirmatoria de VIH, Una prueba de infecciones de transmición sexual y No Sé
<img width="291" alt="screen shot 2017-05-16 at 4 52 09 pm" src="https://cloud.githubusercontent.com/assets/16548492/26129944/194f4b76-3a58-11e7-9920-415224468ba8.png">
