### ISSUE TITLE
El mensaje de bienvenida en el header debe de rotarse

### ISSUE THREAD

**Issue by Josegarcia89** [sindudasmx/sd#5]

**Comment by jipster** [comment]
FIJO: "QuÍtate la duda y hazte la prueba de VIH."
y los mensajes rotativos deben de ser facts sobre el tema en México y el mundo: 56% de las personas que tienen VIH no lo saben.

**Comment by EduardoClark** [comment]
@jipster @Josegarcia89 Ya escribi el codigo para hacerlo aleatorio on load, pero ahora pasenme los copies de los facts que quieren que roten

**Comment by Josegarcia89** [comment]
@jipster ¿Y si vemos con Ricardo que nos pasó copies de esto? Aquí les cambiamos el wording, pero se los podemos pedir. no? Dime para hacerlo

**Comment by Josegarcia89** [comment]
- Los hombres representan 4 de cada 5 nuevos casos de VIH en México 

- 17% de los hombres que tienen sexo con hombres en México, podrían estar viviendo con VIH

- 1 de cada 7 hombres gays nunca se ha hecho una prueba de VIH porque no sabe dónde hacérsela

- La OMS recomienda que los hombres gays y HSH se hagan la prueba de detección del VIH al menos una vez al año 

- La principal razón por la que los hombres gays y bisexuales no usan condón, es porque están en una pareja estable. 

- En México, 1 de cada 3 personas que vive con VIH no lo sabe.  

- Las pruebas rápidas de detección de VIH son igual de buenas que las pruebas de laboratorio 

- Las mujeres trans y los hombres gays son los grupos más afectados por la epidemia del VIH en México 

- Hay más de 50 CAPASITS en todo el país para hacerse la prueba de forma gratuita, rápida y confidencial
