### ISSUE TITLE
Nombres de sitios/clínicas/ONG/Laboratorios en las pantallas interiores

### ISSUE THREAD

**Issue by Josegarcia89** [sindudasmx/sd#58]
En las pantallas interiores, el nombre debe corresponder a la fila de **Institución nombre largo**

<img width="983" alt="screen shot 2017-05-16 at 9 30 51 pm" src="https://cloud.githubusercontent.com/assets/16548492/26136013/049f19c8-3a7f-11e7-901c-7cb28454d45c.png">

**Comment by jipster** [comment]
Siento que esto medio equis no? @Josegarcia89
