### ISSUE TITLE
La info de algunas clínicas se sale del cuadro

### ISSUE THREAD

**Issue by lexielex** [sindudasmx/sd#64]
<img width="278" alt="screen shot 2017-05-17 at 09 17 26" src="https://cloud.githubusercontent.com/assets/13628319/26158525/bd3c160e-3ae1-11e7-9091-0863b3931336.png">

**Comment by jipster** [comment]
Vuelto a revisar los títulos cortos y te aviso cuando esté la base de datos @EduardoClark
