### ISSUE TITLE
Estaría bueno que puedas marcar los teléfonos al dar clic 

### ISSUE THREAD

**Issue by lexielex** [sindudasmx/sd#65]

**Comment by jipster** [comment]
@EduardoClark was looking into that, hay que preguntarle a Rich dijo que es súper fácil

**Comment by lexielex** [comment]
Parece que sí es súper fácil : http://stackoverflow.com/questions/4572297/is-there-a-way-to-make-a-phone-number-clickable-on-an-iphone-or-android-phone-to

**Comment by EduardoClark** [comment]
done solo no esta pusheado yet
