### ISSUE TITLE
Está raro que todas las palabras del footer parecen clickeables (cuando solo el mail lo es)

### ISSUE THREAD

**Issue by lexielex** [sindudasmx/sd#69]
Ejemplo con mouse sobre "Contacto"

<img width="209" alt="screen shot 2017-05-17 at 09 29 05" src="https://cloud.githubusercontent.com/assets/13628319/26159105/4ef627fa-3ae3-11e7-992b-af95bc448719.png">

**Comment by jipster** [comment]
si, ese issue ya estaba, creo que se nos pasó gracias @lexielex
