### ISSUE TITLE
El contenido de algunas tarjetas se sale

### ISSUE THREAD

**Issue by mendozagioo** [sindudasmx/sd#72]
<img width="274" alt="captura de pantalla 2017-05-17 a las 10 25 13 a m" src="https://cloud.githubusercontent.com/assets/1576290/26162484/7a3a06da-3aec-11e7-86c5-28fc17ec1902.png">

Tal vez sea mejor agregarle un scroll o no restringir la altura de cada tarjeta y acomodar todas las tarjetas de acuerdo a su tamaño

**Comment by EduardoClark** [comment]
Ahorita tiene altura fija porque si no se descuadran los cards, ya retrabaje el espacio para que quepa toda la info de la mas larga en la tarjeta.
